name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: d99993e0-8770-427f-b49d-6a536d589392
      ARM_SUBSCRIPTION_ID: 96b73036-7cc0-4f2f-a24c-100e1d9836ca
      ARM_TENANT_ID: af8838c9-b366-4dd8-9820-7b88df50eaab
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_CONFIG_BASE64 }}
    steps:
      - uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Plan
        run: |
          terraform init
          terraform plan --out=out.bin

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/out.bin
          retention-days: 5

  scan:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: d99993e0-8770-427f-b49d-6a536d589392
      ARM_SUBSCRIPTION_ID: 96b73036-7cc0-4f2f-a24c-100e1d9836ca
      ARM_TENANT_ID: af8838c9-b366-4dd8-9820-7b88df50eaab
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_CONFIG_BASE64 }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Scan and Apply
        run: |
          terraform init
          terraform plan -no-color -out plan.tfplan
          terraform show -json plan.tfplan >> plan.json
          terraform apply "plan.tfplan" || true
          git config --global user.name "ozgurozkan123"
          git config --global user.email "ozgurozkan123@hotmail.com"
          git add terraform.tfstate
          git commit -m "Update terraform.tfstate after apply"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ozgurozkan123/devesecops.git main

      - uses: mondoohq/actions/terraform-hcl@v11.0.0
        with:
          path: terraform

      - uses: mondoohq/actions/terraform-state@v11.0.0
        with:
          path: terraform

      - uses: mondoohq/actions/terraform-plan@v11.0.0
        with:
          path: terraform
          plan-file: plan.tfplan

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    env:
      ARM_CLIENT_ID: d99993e0-8770-427f-b49d-6a536d589392
      ARM_SUBSCRIPTION_ID: 96b73036-7cc0-4f2f-a24c-100e1d9836ca
      ARM_TENANT_ID: af8838c9-b366-4dd8-9820-7b88df50eaab
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve terraform/out.bin || true
          git config --global user.name "ozgurozkan123"
          git config --global user.email "ozgurozkan123@hotmail.com"
          git add terraform.tfstate
          git commit -m "Update terraform.tfstate after apply"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ozgurozkan123/devesecops.git main
